
package ch.ahdis.ihe.pix.ddswsclient.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemographicDataServer", targetNamespace = "http://ws.demographic.gazelle.ihe.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemographicDataServer {


    /**
     * 
     * @return
     *     returns java.util.List<ch.ahdis.ihe.pix.ddswsclient.ws.CountryCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListCountryCode", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.GetListCountryCode")
    @ResponseWrapper(localName = "getListCountryCodeResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.GetListCountryCodeResponse")
    public List<CountryCode> getListCountryCode();

    /**
     * 
     * @param countryCode
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.PatientAddress
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnAddress", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddress")
    @ResponseWrapper(localName = "returnAddressResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddressResponse")
    public PatientAddress returnAddress(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param lattitude
     * @param countryCode
     * @param longitude
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.PatientAddress
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnAddressByCoordinates", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddressByCoordinates")
    @ResponseWrapper(localName = "returnAddressByCoordinatesResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddressByCoordinatesResponse")
    public PatientAddress returnAddressByCoordinates(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "lattitude", targetNamespace = "")
        double lattitude,
        @WebParam(name = "longitude", targetNamespace = "")
        double longitude)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param townName
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.PatientAddress
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnAddressByTown", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddressByTown")
    @ResponseWrapper(localName = "returnAddressByTownResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnAddressByTownResponse")
    public PatientAddress returnAddressByTown(
        @WebParam(name = "townName", targetNamespace = "")
        String townName)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param characterSet
     * @param messageType
     * @param countryCode
     * @param hl7Version
     * @param receivingFacility
     * @param receivingApplication
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws HL7Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnHl7Message", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnHl7Message")
    @ResponseWrapper(localName = "returnHl7MessageResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnHl7MessageResponse")
    public String returnHl7Message(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "receivingApplication", targetNamespace = "")
        String receivingApplication,
        @WebParam(name = "receivingFacility", targetNamespace = "")
        String receivingFacility,
        @WebParam(name = "characterSet", targetNamespace = "")
        String characterSet,
        @WebParam(name = "hl7Version", targetNamespace = "")
        String hl7Version,
        @WebParam(name = "messageType", targetNamespace = "")
        String messageType)
        throws HL7Exception_Exception, IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param countryCode1
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod(operationName = "returnHl7v3Message")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnHl7v3Message", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnHl7V3Message")
    @ResponseWrapper(localName = "returnHl7v3MessageResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnHl7V3MessageResponse")
    public String returnHl7V3Message(
        @WebParam(name = "countryCode1", targetNamespace = "")
        String countryCode1)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param genderDescription
     * @param firstNameIs
     * @param countryCode
     * @param firstNameLike
     * @param religionOption
     * @param birthDayOption
     * @param lastNameIs
     * @param raceOption
     * @param lastNameLike
     * @param lastNameOption
     * @param firstNameOption
     * @param addressOption
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.Patient
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPatient", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPatient")
    @ResponseWrapper(localName = "returnPatientResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPatientResponse")
    public Patient returnPatient(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "lastNameOption", targetNamespace = "")
        Boolean lastNameOption,
        @WebParam(name = "firstNameOption", targetNamespace = "")
        Boolean firstNameOption,
        @WebParam(name = "religionOption", targetNamespace = "")
        Boolean religionOption,
        @WebParam(name = "raceOption", targetNamespace = "")
        Boolean raceOption,
        @WebParam(name = "birthDayOption", targetNamespace = "")
        Boolean birthDayOption,
        @WebParam(name = "addressOption", targetNamespace = "")
        Boolean addressOption,
        @WebParam(name = "genderDescription", targetNamespace = "")
        String genderDescription,
        @WebParam(name = "firstNameLike", targetNamespace = "")
        String firstNameLike,
        @WebParam(name = "lastNameLike", targetNamespace = "")
        String lastNameLike,
        @WebParam(name = "firstNameIs", targetNamespace = "")
        String firstNameIs,
        @WebParam(name = "lastNameIs", targetNamespace = "")
        String lastNameIs)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param genderDescription
     * @param motherMaidenNameOption
     * @param aliasNameOption
     * @param maritalSatusOption
     * @param deadPatientOption
     * @param firstNameLike
     * @param displayNameOption
     * @param birthDayOption
     * @param maidenNameOption
     * @param lastNameIs
     * @param lastNameOption
     * @param firstNameOption
     * @param newBornOption
     * @param firstNameIs
     * @param countryCode
     * @param religionOption
     * @param raceOption
     * @param lastNameLike
     * @param addressOption
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.Patient
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPatientWithAllOptions", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPatientWithAllOptions")
    @ResponseWrapper(localName = "returnPatientWithAllOptionsResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPatientWithAllOptionsResponse")
    public Patient returnPatientWithAllOptions(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "lastNameOption", targetNamespace = "")
        Boolean lastNameOption,
        @WebParam(name = "firstNameOption", targetNamespace = "")
        Boolean firstNameOption,
        @WebParam(name = "motherMaidenNameOption", targetNamespace = "")
        Boolean motherMaidenNameOption,
        @WebParam(name = "religionOption", targetNamespace = "")
        Boolean religionOption,
        @WebParam(name = "raceOption", targetNamespace = "")
        Boolean raceOption,
        @WebParam(name = "birthDayOption", targetNamespace = "")
        Boolean birthDayOption,
        @WebParam(name = "addressOption", targetNamespace = "")
        Boolean addressOption,
        @WebParam(name = "genderDescription", targetNamespace = "")
        String genderDescription,
        @WebParam(name = "firstNameLike", targetNamespace = "")
        String firstNameLike,
        @WebParam(name = "lastNameLike", targetNamespace = "")
        String lastNameLike,
        @WebParam(name = "firstNameIs", targetNamespace = "")
        String firstNameIs,
        @WebParam(name = "lastNameIs", targetNamespace = "")
        String lastNameIs,
        @WebParam(name = "maritalSatusOption", targetNamespace = "")
        String maritalSatusOption,
        @WebParam(name = "deadPatientOption", targetNamespace = "")
        Boolean deadPatientOption,
        @WebParam(name = "maidenNameOption", targetNamespace = "")
        Boolean maidenNameOption,
        @WebParam(name = "aliasNameOption", targetNamespace = "")
        Boolean aliasNameOption,
        @WebParam(name = "displayNameOption", targetNamespace = "")
        Boolean displayNameOption,
        @WebParam(name = "newBornOption", targetNamespace = "")
        Boolean newBornOption)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param genderDescription
     * @param motherMaidenNameOption
     * @param firstNameIs
     * @param countryCode
     * @param firstNameLike
     * @param religionOption
     * @param birthDayOption
     * @param lastNameIs
     * @param raceOption
     * @param lastNameLike
     * @param lastNameOption
     * @param firstNameOption
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.Person
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPerson", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPerson")
    @ResponseWrapper(localName = "returnPersonResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnPersonResponse")
    public Person returnPerson(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "lastNameOption", targetNamespace = "")
        boolean lastNameOption,
        @WebParam(name = "firstNameOption", targetNamespace = "")
        boolean firstNameOption,
        @WebParam(name = "motherMaidenNameOption", targetNamespace = "")
        Boolean motherMaidenNameOption,
        @WebParam(name = "religionOption", targetNamespace = "")
        boolean religionOption,
        @WebParam(name = "raceOption", targetNamespace = "")
        boolean raceOption,
        @WebParam(name = "birthDayOption", targetNamespace = "")
        boolean birthDayOption,
        @WebParam(name = "genderDescription", targetNamespace = "")
        String genderDescription,
        @WebParam(name = "firstNameLike", targetNamespace = "")
        String firstNameLike,
        @WebParam(name = "lastNameLike", targetNamespace = "")
        String lastNameLike,
        @WebParam(name = "firstNameIs", targetNamespace = "")
        String firstNameIs,
        @WebParam(name = "lastNameIs", targetNamespace = "")
        String lastNameIs)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param countryCode
     * @return
     *     returns ch.ahdis.ihe.pix.ddswsclient.ws.Patient
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnSimplePatient", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnSimplePatient")
    @ResponseWrapper(localName = "returnSimplePatientResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.ReturnSimplePatientResponse")
    public Patient returnSimplePatient(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode)
        throws IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param targetHost
     * @param characterSet
     * @param messageType
     * @param countryCode
     * @param hl7Version
     * @param receivingFacility
     * @param receivingApplication
     * @param targetPort
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws HL7Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "Hl7MessageRespond", targetNamespace = "")
    @RequestWrapper(localName = "sendHl7Message", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.SendHl7Message")
    @ResponseWrapper(localName = "sendHl7MessageResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.SendHl7MessageResponse")
    public String sendHl7Message(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "targetHost", targetNamespace = "")
        String targetHost,
        @WebParam(name = "targetPort", targetNamespace = "")
        Integer targetPort,
        @WebParam(name = "receivingApplication", targetNamespace = "")
        String receivingApplication,
        @WebParam(name = "receivingFacility", targetNamespace = "")
        String receivingFacility,
        @WebParam(name = "characterSet", targetNamespace = "")
        String characterSet,
        @WebParam(name = "hl7Version", targetNamespace = "")
        String hl7Version,
        @WebParam(name = "messageType", targetNamespace = "")
        String messageType)
        throws HL7Exception_Exception, IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param systemName
     * @param countryCode
     * @param receivingFacility
     * @param receivingApplication
     * @param url
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws JDOMException_Exception
     * @throws HL7Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod(operationName = "sendHl7v3Message")
    @WebResult(name = "Hl7v3MessageRespond", targetNamespace = "")
    @RequestWrapper(localName = "sendHl7v3Message", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.SendHl7V3Message")
    @ResponseWrapper(localName = "sendHl7v3MessageResponse", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", className = "ch.ahdis.ihe.pix.ddswsclient.ws.SendHl7V3MessageResponse")
    public String sendHl7V3Message(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode,
        @WebParam(name = "systemName", targetNamespace = "")
        String systemName,
        @WebParam(name = "url", targetNamespace = "")
        String url,
        @WebParam(name = "receivingApplication", targetNamespace = "")
        String receivingApplication,
        @WebParam(name = "receivingFacility", targetNamespace = "")
        String receivingFacility)
        throws HL7Exception_Exception, IOException_Exception, JDOMException_Exception, SOAPException_Exception
    ;

}
