
package ch.ahdis.ihe.pix.ddswsclient.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemographicDataServerService", targetNamespace = "http://ws.demographic.gazelle.ihe.net/", wsdlLocation = "file:/Users/oliveregger/Documents/workspaceDocker/ddswsclient/src/main/resources/DemographicDataServerService.wsdl")
public class DemographicDataServerService
    extends Service
{

    private final static URL DEMOGRAPHICDATASERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOGRAPHICDATASERVERSERVICE_EXCEPTION;
    private final static QName DEMOGRAPHICDATASERVERSERVICE_QNAME = new QName("http://ws.demographic.gazelle.ihe.net/", "DemographicDataServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/oliveregger/Documents/workspaceDocker/ddswsclient/src/main/resources/DemographicDataServerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOGRAPHICDATASERVERSERVICE_WSDL_LOCATION = url;
        DEMOGRAPHICDATASERVERSERVICE_EXCEPTION = e;
    }

    public DemographicDataServerService() {
        super(__getWsdlLocation(), DEMOGRAPHICDATASERVERSERVICE_QNAME);
    }


    public DemographicDataServerService(URL wsdlLocation) {
        super(wsdlLocation, DEMOGRAPHICDATASERVERSERVICE_QNAME);
    }


    public DemographicDataServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns DemographicDataServer
     */
    @WebEndpoint(name = "DemographicDataServerPort")
    public DemographicDataServer getDemographicDataServerPort() {
        return super.getPort(new QName("http://ws.demographic.gazelle.ihe.net/", "DemographicDataServerPort"), DemographicDataServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemographicDataServer
     */
    @WebEndpoint(name = "DemographicDataServerPort")
    public DemographicDataServer getDemographicDataServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.demographic.gazelle.ihe.net/", "DemographicDataServerPort"), DemographicDataServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOGRAPHICDATASERVERSERVICE_EXCEPTION!= null) {
            throw DEMOGRAPHICDATASERVERSERVICE_EXCEPTION;
        }
        return DEMOGRAPHICDATASERVERSERVICE_WSDL_LOCATION;
    }

}
